syntax = "proto3";

//Used to prefix so CPP native code can directly use the message name
package PROTO;

//Audiolink feature set support checklist
/*
Waveform ✓
Spectrogram ✓
4 Band (32 history) ✓
4 Band (128 history) ✓
4 Band Filtered ✓
ColorChord
Autocorrelator
Floating Autocorrelator
VU Meter Left
VU Meter Left+Right
Filtered VU meter
AudioLink FPS
AudioLink Version Read
Synced Instance Time
Chronotensity
ColorChord Index Colors
Theme Colors ✓
UTC Time
Global Strings
Media States
*/

//"Primitive" type
message Color {
    float R = 1;
    float G = 2;
    float B = 3;
}

message ThemeColors {
    Color ThemeColor0 = 1; // ✓
    Color ThemeColor1 = 2; // ✓
    Color ThemeColor2 = 3; // ✓
    Color ThemeColor3 = 4; // ✓
}

//hard to decide right now if things should be halfs or bytes

message DFT {
    repeated float mag = 1 [packed=true]; // ✓
    repeated float magEQ = 2 [packed=true]; // ✓
    repeated float magfilt = 3 [packed=true]; // ✓
    repeated float magPhase = 4 [packed=true]; // ✓
}

message History {
    repeated float bass = 1 [packed=true]; // ✓
    repeated float lowmid = 2 [packed=true]; // ✓
    repeated float highmid = 3 [packed=true]; // ✓
    repeated float treble = 4 [packed=true]; // ✓
}

//4 x 16
message FilteredAudiolink {
    repeated float bass = 1 [packed=true]; // ✓
    repeated float lowmid = 2 [packed=true]; // ✓
    repeated float highmid = 3 [packed=true]; // ✓
    repeated float treble = 4 [packed=true]; // ✓
}

message WaveForm {
    //24,000 SPS audio, amplitude. Contains 2046 samples.
    repeated float wav1 = 1 [packed=true]; // ✓
    //48,000 SPS audio, amplitude. Contains 2048 samples.
    repeated float wav2 = 2 [packed=true]; // ✓
    //12,000 SPS audio, amplitude. Contains 1023 samples.
    repeated float wav3 = 3 [packed=true]; // ✓
    //24,000 SPS audio, differential. For left channel take wav1 + wav1diff, for right channel take wav1 - wav1diff. Contains 2046 samples.
    repeated float wav1diff = 4 [packed=true]; // ✓
}

//enum for playback state
enum PlaybackState {
    PLAYBACK_STATE_NONE = 0; // ✓
    PLAYBACK_STATE_PLAYING = 1; // ✓
    PLAYBACK_STATE_PAUSED = 2; // ✓
    PLAYBACK_STATE_STOPPED = 3; // ✓
    PLAYBACK_STATE_LOADING = 4; // ✓
    PLAYBACK_STATE_STREAMING = 5; // ✓
    PLAYBACK_STATE_ERROR = 6; // ✓
}

enum LoopOrRandom {
    LOOP_OR_RANDOM_NONE = 0; // ✓
    LOOP_OR_RANDOM_LOOP = 1; // ✓
    LOOP_OR_RANDOM_LOOP_ONE = 2; // ✓
    LOOP_OR_RANDOM_RANDOM = 3; // ✓
    LOOP_OR_RANDOM_RANDOM_AND_LOOP = 4; // ✓
}

message MediaState {
    //0 to 1
    float mediaVolume = 1; // ✓
    //0 to 1
    float mediaTime = 2; // ✓
    PlaybackState mediaPlayback = 3; // ✓
    LoopOrRandom mediaLoop = 4; // ✓
}

message PlayerData {
    uint32 numberOfPlayers = 1; // ✓
    bool isMaster = 2; // ✓
    bool isOwner = 3; // ✓
}

message Intensity {
    float RMSLeft = 1; // ✓
    float PeakLeft = 2; // ✓
    float RMSRight = 3; // ✓
    float PeakRight = 4; // ✓
}

message Autogain {
    float asymmetricGain = 1; // ✓
    float symmetricGain = 2; // ✓
}

message Position {
    double lat = 1; // ✓
    double lon = 2; // ✓
}

message GeneralVU { //TODO: Optimize some of these down to uint32's / uint64's?
    float versionMajor = 1; // ✓
    float versionMinor = 2; // ✓
    float systemFPS = 3; // ✓
    float frameCount = 4; // ✓
    //TODO: Delineate all of these from eachother
    //IDEA: Instance start means event start
    //  TODO: Implement a way to enter when the event starts for this one. Right now it mirrors midnight local
    //Network time indicates since transmitter/encoder boot?
    //  sidenote, audiolink already makes it work this way which is cool
    //then midnight local stays correct
    double msSinceInstanceStart = 5; // ✓
    double msSinceMidnightLocal = 6; // ✓
    double msInNetworkTime = 7; // ✓
    //TODO: Figure out CDJ protocols or such for all of these, would be cool to send track info
    MediaState media_state = 8; // ✓
    //TODO: Send event attendee information for this one
    //not sure what to do for is owner and is master. Maybe just drop them to be honest idk
    PlayerData player_data = 9; // ✓
    Intensity current_intensity = 10; // ✓
    Intensity marker_value = 11; // ✓
    Intensity marker_times = 12; // ✓
    Autogain autogain = 13; // ✓
    double UTCDaysSinceEpoch = 14; // ✓
    //this may not be correct, need to verify
    //appears to be 10 hours behind UTC time. PST based?
    double msSinceUTCDayStart = 15; // ✓
    Position position = 16; //Position of the Audiolink AudioSource in worldspace. Using lat lon for some fun opportunities
}

message ColorChord {
    repeated Color colors = 1; // ✓
    repeated Color strip = 2; // ✓
    repeated Color lights_internal = 3; // ✓
    repeated Color lights = 4; // ✓
}

message AutoCorrelator {
    repeated float autocorrelation = 1 [packed=true]; // ✓
    repeated float uncorrelated = 2 [packed=true]; // ✓
}

//from audiolink docs
/*
0	Motion increases as intensity of band increases. It does not go backwards.
1	Same as above but uses ALPASS_FILTERAUDIOLINK instead of ALPASS_AUDIOLINK
2	Motion moves back and forth as a function of intensity.
3	Same as above but uses ALPASS_FILTERAUDIOLINK instead of ALPASS_AUDIOLINK
4	Fixed speed increase when the band is dark. Stationary when light.
5	Same as above but uses ALPASS_FILTERAUDIOLINK instead of ALPASS_AUDIOLINK
6	Fixed speed increase when the band is dark. Fixed speed decrease when light.
7	Same as above but uses ALPASS_FILTERAUDIOLINK instead of ALPASS_AUDIOLINK.
*/
message ChronotensityBand {
    uint32 increasing = 1; // ✓
    uint32 filtered_increasing = 2; // ✓
    uint32 bounce = 3; // ✓
    uint32 filtered_bounce = 4; // ✓
    uint32 intensity_pause = 5; // ✓
    uint32 filtered_intensity_pause = 6; // ✓
    uint32 bounce_pause = 7; // ✓
    uint32 filtered_bounce_pause = 8; // ✓
}

message Chronotensity {
    ChronotensityBand bass = 1; // ✓
    ChronotensityBand lowmid = 2; // ✓
    ChronotensityBand highmid = 3; // ✓
    ChronotensityBand treble = 4; // ✓
}

//each string is 0 to 31 long
message GlobalStrings {
    string playerName = 1; // ✓
    string masterName = 2; // ✓
    //Possibly bsky bot or hashtag data
    //Marquee if more than 32 characters
    string customString1 = 3; // ✓
    string customString2 = 4; // ✓
}

message Audiolink_Data {
    History history = 1; // ✓
    ThemeColors theme_colors = 2; // ✓
    DFT dft = 3; // ✓
    FilteredAudiolink filtered_audiolink = 4; // ✓
    //Not sent currently as it utterly packs the data and causes a bunch of packets to be sent
    //Unclear if anyone will ever use it. Potentially look into higher data rate systems to resolve this
    WaveForm waveform = 5; // ✓
    GeneralVU general_vu = 6; // ✓
    ColorChord colorchord = 7; // ✓
    AutoCorrelator autocorrelator = 8; // ✓
    Chronotensity chronotensity = 9; // ✓
    GlobalStrings global_strings = 10; // ✓
}

message Sub_Packet {
    //current packet INSIDE the full packet
    int32 packet_index = 1; // ✓
    //total packets in the full packet
    int32 packet_count = 3; // ✓
    //commented out to explore zh_network instead https://github.com/aZholtikov/zh_network
    // //UNIMPLEMENTED:
    // //TODO: Create a NEW project that is purely for retransmitters
    // //take in esp-now packets with sub_packet definition, add themselves to the retransmitters list, and retransmit them. This will allow for a mesh network of audiolink data to be sent around to help with range and reliability
    // //current frame number of the full packet. This is incremented and looped around at 2^31-1. This is used to determine if a packet is old or new at the receiver
    // //IE, if the receiver gets frame number 5, and a retransmitter is delayed and sends out a packet for frame 4, we know its invalid as its behind, so we can just ignore it.
    // //ANOTHER TODO: Receivers should try to wait until until the last possible moment that all packets could have arrived to decode.
    // int32 frame_number = 4;
    // //list of mac addresses (truncated) that have already retransmitted this packet. This is used to prevent infinite loops of retransmission
    // //this list should also be hardcoded to a limit to prevent growing the sub packet size beyond esp-nows limit. if we hit that count limit, even if we arent in the list, just drop the packet.
    // repeated int32 retransmitters = 6;
    //arbitrary data
    repeated bytes data = 2; // ✓
}
